enum FirebaseStatus {
    AUTHENTICATING = 'AUTHENTICATING',
    AUTHENTICATED = 'AUTHENTICATED',
    UNAUTHENTICATED = 'UNAUTHENTICATED',
    CHECKING = 'CHECKING',
    ERROR = 'ERROR'
}

export default FirebaseStatus;